import type { PathUnit } from "../lessonPathTypes";

export const apisUnits: PathUnit[] = [
  {
    id: "fundamentals",
    title: "Fundamentals",
    color: "#5b9dff",
    lessons: [
      {
        id: "api-fund-1",
        title: "What is an API?",
        question: "In simple terms, what is an API?",
        options: [
          "A type of database",
          "A defined way for one piece of software to request or send data to another",
          "A programming language",
          "A web browser feature",
        ],
        correctIndex: 1,
        explanation: "An API is the agreed contract that lets separate pieces of software communicate predictably.",
      },
      {
        id: "api-fund-2",
        title: "Client and server",
        question: "Who is the 'client' in a client/server interaction?",
        options: [
          "Whoever receives the request and responds",
          "Whoever initiates the request",
          "The database only",
          "There is no client in APIs",
        ],
        correctIndex: 1,
        explanation: "The client is whoever makes the request; the server receives it and responds.",
      },
      {
        id: "api-fund-3",
        title: "Web APIs",
        question: "What protocol do most modern web APIs run over?",
        options: ["FTP", "SMTP", "HTTP", "SSH"],
        correctIndex: 2,
        explanation: "Web APIs typically use HTTP/HTTPS, the same protocol browsers use to load pages.",
      },
      {
        id: "api-fund-4",
        title: "Dual role",
        question: "Can the same machine be both a client and a server?",
        options: [
          "No, a machine is always one or the other",
          "Yes — e.g. a backend is a server to its frontend but a client when calling a third-party API",
          "Only mobile devices can do this",
          "Only true for databases",
        ],
        correctIndex: 1,
        explanation: "Role depends on context: the same system can serve one caller while calling another service itself.",
      },
      {
        id: "api-fund-5",
        title: "Why APIs matter",
        question: "Why do developers spend so much time working with APIs?",
        options: [
          "APIs are required by law",
          "Nearly all software relies on talking to other software, both consuming and exposing APIs",
          "APIs replace the need for databases",
          "Only backend developers ever touch APIs",
        ],
        correctIndex: 1,
        explanation: "Calling and building APIs is one of the most universal skills across software roles.",
      },
      {
        id: "api-fund-6",
        title: "Request/response",
        question: "What is the basic structure of an HTTP API interaction?",
        options: [
          "The client sends a request, the server sends back a response",
          "The server polls the client constantly",
          "There's no structure, it's freeform",
          "Only the server can initiate communication",
        ],
        correctIndex: 0,
        explanation: "HTTP follows a request/response model: the client asks, the server answers.",
      },
    ],
  },
  {
    id: "http",
    title: "HTTP Essentials",
    color: "#3ecf8e",
    lessons: [
      {
        id: "api-http-1",
        title: "HTTP methods",
        question: "Which HTTP method is meant for creating a new resource?",
        options: ["GET", "POST", "DELETE", "OPTIONS"],
        correctIndex: 1,
        explanation: "POST is conventionally used to create new resources, with data in the request body.",
      },
      {
        id: "api-http-2",
        title: "GET vs PUT vs PATCH",
        question: "What's the difference between PUT and PATCH?",
        options: [
          "They are identical",
          "PUT replaces a resource entirely; PATCH partially updates it",
          "PUT is for reading; PATCH is for writing",
          "PATCH always deletes data",
        ],
        correctIndex: 1,
        explanation: "PUT typically sends the full replacement resource; PATCH sends only the fields to change.",
      },
      {
        id: "api-http-3",
        title: "2xx status codes",
        question: "What does a `201` status code typically mean?",
        options: ["The request failed", "A new resource was successfully created", "The server is redirecting", "Rate limit exceeded"],
        correctIndex: 1,
        explanation: "201 Created confirms a new resource was made, often returned after a successful POST.",
      },
      {
        id: "api-http-4",
        title: "4xx vs 5xx",
        question: "What's the general distinction between 4xx and 5xx status codes?",
        options: [
          "4xx means client error; 5xx means server error",
          "4xx means success; 5xx means failure",
          "They're interchangeable",
          "4xx is for GET only; 5xx for POST only",
        ],
        correctIndex: 0,
        explanation: "4xx means the client did something unexpected (bad input, missing auth); 5xx means the server itself broke.",
      },
      {
        id: "api-http-5",
        title: "401 vs 403",
        question: "What's the difference between a 401 and a 403 status code?",
        options: [
          "There is no difference",
          "401 means not authenticated; 403 means authenticated but not allowed",
          "401 is a server error; 403 is a client error",
          "403 always means the URL is wrong",
        ],
        correctIndex: 1,
        explanation: "401 means 'we don't know who you are'; 403 means 'we know who you are, but you can't do this.'",
      },
      {
        id: "api-http-6",
        title: "JSON",
        question: "Which data format do most modern APIs use to exchange data?",
        options: ["XML only", "CSV", "JSON", "Plain text only"],
        correctIndex: 2,
        explanation: "JSON (JavaScript Object Notation) is the near-universal format for API requests/responses.",
      },
    ],
  },
  {
    id: "rest-design",
    title: "REST Design",
    color: "#c792ea",
    lessons: [
      {
        id: "api-rest-1",
        title: "Resources as nouns",
        question: "Which URL design follows REST conventions?",
        options: ["GET /getAllUsers", "POST /deleteUser", "DELETE /users/42", "GET /user-deletion-action"],
        correctIndex: 2,
        explanation: "REST models resources as nouns (/users/42) and uses the HTTP method to express the action.",
      },
      {
        id: "api-rest-2",
        title: "Statelessness",
        question: "What does it mean for a REST API to be 'stateless'?",
        options: [
          "It never stores any data",
          "Each request contains everything needed to process it, with no memory of past requests",
          "It only works with static websites",
          "It can't be used by mobile apps",
        ],
        correctIndex: 1,
        explanation: "Statelessness means the server doesn't rely on remembering previous interactions.",
      },
      {
        id: "api-rest-3",
        title: "Query parameters",
        question: "What are query parameters (`?key=value`) typically used for?",
        options: [
          "Authenticating the user",
          "Filtering, sorting, and pagination on GET requests",
          "Defining the HTTP method",
          "Encrypting the request",
        ],
        correctIndex: 1,
        explanation: "Query params are optional modifiers, commonly used for filtering/sorting/pagination.",
      },
      {
        id: "api-rest-4",
        title: "Nested resources",
        question: "What does `GET /articles/7/comments` represent?",
        options: [
          "Deleting article 7",
          "Listing the comments belonging to article 7",
          "Creating a new article",
          "An invalid URL",
        ],
        correctIndex: 1,
        explanation: "Nesting a resource under another represents a sub-collection — comments belonging to article 7.",
      },
      {
        id: "api-rest-5",
        title: "Versioning",
        question: "Why do APIs often include a version in the URL, like `/v1/articles`?",
        options: [
          "It's required by HTTP",
          "So old consumers keep working on v1 while new features land in v2 without breaking them",
          "It makes responses smaller",
          "It's purely cosmetic",
        ],
        correctIndex: 1,
        explanation: "Versioning lets an API evolve without breaking existing integrations that depend on old behavior.",
      },
      {
        id: "api-rest-6",
        title: "Pagination",
        question: "Why would an API paginate a large list response (e.g. `?page=2&limit=20`)?",
        options: [
          "To intentionally slow down clients",
          "To avoid sending huge amounts of data in a single response",
          "Pagination is purely a security feature",
          "It's required by the JSON spec",
        ],
        correctIndex: 1,
        explanation: "Pagination breaks large result sets into manageable chunks instead of one massive response.",
      },
    ],
  },
  {
    id: "auth-security",
    title: "Auth & Security",
    color: "#ffb454",
    lessons: [
      {
        id: "api-auth-1",
        title: "AuthN vs AuthZ",
        question: "What's the difference between authentication and authorization?",
        options: [
          "They're the same thing",
          "Authentication proves identity; authorization determines what that identity can do",
          "Authentication is for servers; authorization is for clients",
          "Authorization always happens before authentication",
        ],
        correctIndex: 1,
        explanation: "Authentication = 'who are you'; authorization = 'what can you do.'",
      },
      {
        id: "api-auth-2",
        title: "API keys",
        question: "How are API keys typically used to identify a calling application?",
        options: [
          "Embedded visibly in the page title",
          "Sent in a header or query parameter, like a password for the app",
          "They are never sent over the network",
          "They replace the need for HTTPS",
        ],
        correctIndex: 1,
        explanation: "API keys are sent with each request (often as a header) and should be treated like secrets.",
      },
      {
        id: "api-auth-3",
        title: "Bearer tokens",
        question: "What does sending `Authorization: Bearer <token>` typically prove?",
        options: [
          "Nothing, it's just a convention",
          "That the request comes from an authenticated user/session",
          "That the request is from a search engine",
          "That the data is encrypted",
        ],
        correctIndex: 1,
        explanation: "Bearer tokens (often JWTs) prove an authenticated session, usually with an expiration.",
      },
      {
        id: "api-auth-4",
        title: "OAuth",
        question: "What problem does OAuth solve?",
        options: [
          "It speeds up API responses",
          "It lets a user grant a third-party app limited access without sharing their actual password",
          "It replaces HTTP with a faster protocol",
          "It compresses JSON responses",
        ],
        correctIndex: 1,
        explanation: "OAuth enables delegated access (e.g. 'Sign in with Google') without handing over credentials.",
      },
      {
        id: "api-auth-5",
        title: "Storing secrets",
        question: "Where should API keys and secrets be stored?",
        options: [
          "Hardcoded directly in the source code",
          "In environment variables, kept out of source control",
          "In a public GitHub repository for transparency",
          "In the URL of every request",
        ],
        correctIndex: 1,
        explanation: "Environment variables (and .gitignore for secret files) keep credentials out of your codebase.",
      },
      {
        id: "api-auth-6",
        title: "HTTPS",
        question: "Why must real data exchange always use HTTPS instead of plain HTTP?",
        options: [
          "HTTPS is just a faster version of HTTP",
          "HTTP sends data in plain text, readable by anyone intercepting the connection",
          "HTTP doesn't support JSON",
          "There's no real difference",
        ],
        correctIndex: 1,
        explanation: "HTTPS encrypts traffic; plain HTTP exposes data to anyone who can intercept the connection.",
      },
    ],
  },
  {
    id: "working-with-apis",
    title: "Working with APIs",
    color: "#ff8a8a",
    lessons: [
      {
        id: "api-work-1",
        title: "Reading docs",
        question: "What should you look for first when learning a new, unfamiliar API?",
        options: [
          "The most complex write endpoint available",
          "The smallest working example, often a GET request needing no auth",
          "The pricing page",
          "The API's internal source code",
        ],
        correctIndex: 1,
        explanation: "Starting with the simplest possible call builds confidence before attempting writes/auth.",
      },
      {
        id: "api-work-2",
        title: "curl and Postman",
        question: "What are tools like curl and Postman commonly used for?",
        options: [
          "Writing API documentation",
          "Manually sending HTTP requests to test and explore an API",
          "Compiling code",
          "Hosting an API",
        ],
        correctIndex: 1,
        explanation: "They let developers send requests and inspect responses without writing a full client app.",
      },
      {
        id: "api-work-3",
        title: "Rate limiting",
        question: "What does a `429 Too Many Requests` status code indicate?",
        options: [
          "The request succeeded",
          "The server crashed",
          "The client has exceeded the allowed rate limit of requests",
          "The resource was permanently moved",
        ],
        correctIndex: 2,
        explanation: "429 signals the client should slow down — it has exceeded the API's allowed request rate.",
      },
      {
        id: "api-work-4",
        title: "Caching",
        question: "Why might an API response include caching headers (like `Cache-Control`)?",
        options: [
          "To force clients to always refetch data",
          "To let clients avoid unnecessary repeat requests for data that hasn't changed",
          "Caching headers are purely decorative",
          "To slow down the API intentionally",
        ],
        correctIndex: 1,
        explanation: "Cache headers tell clients/proxies how long a response can be reused before refetching.",
      },
      {
        id: "api-work-5",
        title: "Webhooks",
        question: "How does a webhook differ from a typical API call?",
        options: [
          "A webhook is just another name for a GET request",
          "Instead of the client asking for data, the server pushes data to the client when an event happens",
          "Webhooks only work over FTP",
          "There is no difference",
        ],
        correctIndex: 1,
        explanation: "Webhooks invert the usual flow: the server calls a URL you provide when something happens.",
      },
    ],
  },
  {
    id: "advanced-concepts",
    title: "Advanced Concepts",
    color: "#9d8cff",
    lessons: [
      {
        id: "api-adv-1",
        title: "REST vs GraphQL",
        question: "What is a key difference between REST and GraphQL?",
        options: [
          "GraphQL doesn't use HTTP at all",
          "GraphQL lets clients request exactly the fields they need in a single query, instead of fixed endpoints",
          "REST is always faster than GraphQL",
          "They are exactly the same",
        ],
        correctIndex: 1,
        explanation: "GraphQL exposes a flexible query language so clients can shape responses, unlike REST's fixed resource shapes.",
      },
      {
        id: "api-adv-2",
        title: "WebSockets",
        question: "When would you reach for WebSockets instead of regular HTTP requests?",
        options: [
          "For a one-time form submission",
          "For real-time, two-way communication like a chat app",
          "For serving static images",
          "WebSockets replace JSON entirely",
        ],
        correctIndex: 1,
        explanation: "WebSockets keep a persistent connection open, ideal for continuous real-time updates in both directions.",
      },
      {
        id: "api-adv-3",
        title: "CORS",
        question: "What problem does CORS (Cross-Origin Resource Sharing) address?",
        options: [
          "It speeds up database queries",
          "It controls whether a browser is allowed to let JavaScript from one origin call an API on another origin",
          "It encrypts API traffic",
          "It replaces authentication",
        ],
        correctIndex: 1,
        explanation: "CORS is a browser security mechanism governing cross-origin requests from client-side JavaScript.",
      },
      {
        id: "api-adv-4",
        title: "API gateways",
        question: "What is the role of an API gateway in a system with many microservices?",
        options: [
          "It stores the application's database",
          "It acts as a single entry point, routing requests and handling concerns like auth and rate limiting centrally",
          "It compiles the application code",
          "It is only used for testing",
        ],
        correctIndex: 1,
        explanation: "An API gateway centralizes cross-cutting concerns (routing, auth, rate limiting) in front of many services.",
      },
      {
        id: "api-adv-5",
        title: "Microservices",
        question: "In a microservices architecture, how do services typically communicate?",
        options: [
          "They share one giant in-memory object",
          "Over the network, often via APIs (HTTP/REST, gRPC, or messaging)",
          "Only through a shared file on disk",
          "They never communicate directly",
        ],
        correctIndex: 1,
        explanation: "Independent services usually communicate over the network via APIs rather than sharing memory.",
      },
    ],
  },
  {
    id: "error-handling",
    title: "Error Handling & Reliability",
    color: "#5bd1ff",
    lessons: [
      {
        id: "api-err-1",
        title: "Error response design",
        question: "What makes a well-designed API error response helpful?",
        options: [
          "Returning a 200 status code for everything",
          "An appropriate status code plus a clear, structured error message/body",
          "An empty response body",
          "Returning the server's raw stack trace to all clients",
        ],
        correctIndex: 1,
        explanation: "Good errors combine a meaningful status code with a structured message clients can act on.",
      },
      {
        id: "api-err-2",
        title: "Retries",
        question: "When is it generally safe to automatically retry a failed API request?",
        options: [
          "Always, regardless of the operation",
          "For idempotent operations (like GET) or with idempotency keys, especially on transient errors like timeouts",
          "Never retry under any circumstances",
          "Only for DELETE requests",
        ],
        correctIndex: 1,
        explanation: "Retrying non-idempotent operations blindly can cause duplicate effects (e.g. double charges).",
      },
      {
        id: "api-err-3",
        title: "Timeouts",
        question: "Why should an API client set a request timeout?",
        options: [
          "To make requests fail randomly",
          "To avoid waiting indefinitely if the server is slow or unresponsive",
          "Timeouts are not needed for HTTP",
          "To bypass authentication",
        ],
        correctIndex: 1,
        explanation: "Timeouts prevent a client from hanging forever if the server never responds.",
      },
      {
        id: "api-err-4",
        title: "Idempotency",
        question: "What does it mean for an API operation to be 'idempotent'?",
        options: [
          "It always fails the second time it's called",
          "Calling it multiple times with the same input produces the same result as calling it once",
          "It can only be called once ever",
          "It must use the POST method",
        ],
        correctIndex: 1,
        explanation: "GET, PUT, and DELETE are typically idempotent — repeating them has the same effect as doing it once.",
      },
      {
        id: "api-err-5",
        title: "Circuit breakers",
        question: "What is the purpose of a 'circuit breaker' pattern when calling another service?",
        options: [
          "To permanently disable a failing API",
          "To stop sending requests to a failing dependency temporarily, preventing cascading failures",
          "To increase the rate limit",
          "To encrypt traffic",
        ],
        correctIndex: 1,
        explanation: "Circuit breakers detect repeated failures and 'open' to stop hammering a struggling dependency.",
      },
    ],
  },
  {
    id: "practice",
    title: "Real-World Practice",
    color: "#5bff9d",
    lessons: [
      {
        id: "api-prac-1",
        title: "Choosing a method",
        question: "A client needs to update only the email field of a user. Which method best fits?",
        options: ["GET", "PATCH", "DELETE", "OPTIONS"],
        correctIndex: 1,
        explanation: "PATCH is for partial updates — changing just one field, not replacing the whole resource.",
      },
      {
        id: "api-prac-2",
        title: "Designing endpoints",
        question: "Which endpoint design best follows REST conventions for fetching a single order?",
        options: ["/getOrder?id=42", "/orders/42", "/order-fetch/42", "/api?action=order&id=42"],
        correctIndex: 1,
        explanation: "Resource-oriented URLs use nouns and path segments, not verbs or action query params.",
      },
      {
        id: "api-prac-3",
        title: "Debugging a 403",
        question: "A request returns 403 Forbidden. What does that most likely mean?",
        options: [
          "The server is down",
          "The user is authenticated but not allowed to perform this action",
          "The URL doesn't exist",
          "The request body is malformed JSON",
        ],
        correctIndex: 1,
        explanation: "403 means identity is known, but the action/resource isn't permitted for that identity.",
      },
      {
        id: "api-prac-4",
        title: "Handling rate limits",
        question: "Your client keeps getting 429 responses. What's the appropriate fix?",
        options: [
          "Immediately retry in a tight loop",
          "Back off and slow down requests, respecting any Retry-After header",
          "Switch to a different HTTP method",
          "Ignore the status code and proceed",
        ],
        correctIndex: 1,
        explanation: "Respecting rate limits with backoff avoids getting blocked further and is the considerate approach.",
      },
      {
        id: "api-prac-5",
        title: "Securing a public endpoint",
        question: "You're building a public API that costs you money per request. What's the most important protection to add?",
        options: [
          "Nothing, public APIs don't need protection",
          "Authentication/API keys plus rate limiting to control usage and cost",
          "Just slower servers",
          "Removing all documentation",
        ],
        correctIndex: 1,
        explanation: "Combining auth (to identify callers) with rate limiting (to cap usage) protects cost and stability.",
      },
      {
        id: "api-prac-6",
        title: "Versioned breaking change",
        question: "You need to change a field's data type in your API's response. What's the safest approach?",
        options: [
          "Change it immediately in the existing endpoint for everyone",
          "Release the change as a new API version (e.g. /v2/) so existing consumers aren't broken",
          "Email all unknown consumers individually before changing anything",
          "Breaking changes are unavoidable, just ship it",
        ],
        correctIndex: 1,
        explanation: "Versioning lets you introduce breaking changes without disrupting consumers still on the old version.",
      },
    ],
  },
];

export const allApisLessons = apisUnits.flatMap((u) => u.lessons);
