import type { PathUnit } from "../lessonPathTypes";

export const pythonUnits: PathUnit[] = [
  {
    id: "basics",
    title: "Basics",
    color: "#5b9dff",
    lessons: [
      {
        id: "py-var-1",
        title: "Variables",
        question: "Which of these is a valid Python variable assignment?",
        options: ["name => 'Ada'", "name = 'Ada'", "let name = 'Ada'", "var name == 'Ada'"],
        correctIndex: 1,
        explanation: "Python uses a single `=` for assignment. No `let`/`var` keyword is needed.",
      },
      {
        id: "py-var-2",
        title: "Type inference",
        question: "What type does Python infer for `height = 1.7`?",
        options: ["int", "float", "str", "bool"],
        correctIndex: 1,
        explanation: "Any number written with a decimal point is a float.",
      },
      {
        id: "py-var-3",
        title: "Core types",
        question: "Which of these is NOT a Python built-in type?",
        options: ["str", "int", "char", "bool"],
        correctIndex: 2,
        explanation: "Python has no separate `char` type — single characters are just strings of length 1.",
      },
      {
        id: "py-var-4",
        title: "f-strings",
        question: "What does `print(f\"Hi {name}\")` do if `name = \"Ada\"`?",
        options: ["Prints 'Hi {name}'", "Throws an error", "Prints 'Hi Ada'", "Prints 'Hi' only"],
        correctIndex: 2,
        explanation: "The `f` prefix enables embedding variable values directly inside `{}` braces.",
      },
      {
        id: "py-var-5",
        title: "Operators",
        question: "What does `10 % 3` evaluate to?",
        options: ["3", "3.33", "1", "0"],
        correctIndex: 2,
        explanation: "% is the modulo operator, returning the remainder — 10 divided by 3 leaves remainder 1.",
      },
      {
        id: "py-var-6",
        title: "Comments",
        question: "How do you write a single-line comment in Python?",
        options: ["// comment", "<!-- comment -->", "# comment", "/* comment */"],
        correctIndex: 2,
        explanation: "Python uses `#` to start a comment that runs to the end of the line.",
      },
    ],
  },
  {
    id: "control-flow",
    title: "Control Flow",
    color: "#3ecf8e",
    lessons: [
      {
        id: "py-cf-1",
        title: "if/elif/else",
        question: "What defines a code block in Python instead of curly braces?",
        options: ["Semicolons", "Indentation", "Parentheses", "The word 'block'"],
        correctIndex: 1,
        explanation: "Python relies on consistent indentation to know which lines belong inside a block.",
      },
      {
        id: "py-cf-2",
        title: "Comparisons",
        question: "What is the difference between `=` and `==`?",
        options: [
          "No difference",
          "= assigns a value; == checks equality",
          "= is for numbers, == for strings",
          "== assigns; = checks equality",
        ],
        correctIndex: 1,
        explanation: "= is assignment. == is a comparison returning True or False.",
      },
      {
        id: "py-cf-3",
        title: "for loops",
        question: "What does `range(5)` produce when looped over?",
        options: ["1, 2, 3, 4, 5", "0, 1, 2, 3, 4", "5 only", "0 through 5"],
        correctIndex: 1,
        explanation: "range(5) generates 5 numbers starting at 0, so 0 through 4.",
      },
      {
        id: "py-cf-4",
        title: "for over lists",
        question: "What does `for fruit in [\"a\", \"b\"]: print(fruit)` print?",
        options: ["a\\nb", "[\"a\", \"b\"]", "fruit\\nfruit", "An error"],
        correctIndex: 0,
        explanation: "The loop binds `fruit` to each list item in turn and prints it.",
      },
      {
        id: "py-cf-5",
        title: "while loops",
        question: "When does a `while` loop stop running?",
        options: [
          "After exactly 10 iterations",
          "When its condition becomes false",
          "When it encounters the first print()",
          "Never, unless break is called",
        ],
        correctIndex: 1,
        explanation: "A while loop keeps running as long as its condition evaluates to True.",
      },
      {
        id: "py-cf-6",
        title: "break vs continue",
        question: "What does `continue` do inside a loop?",
        options: [
          "Ends the loop immediately",
          "Skips the rest of the current iteration and moves to the next one",
          "Pauses the program",
          "Restarts the loop from the beginning",
        ],
        correctIndex: 1,
        explanation: "continue jumps straight to the next iteration, skipping remaining code for the current one.",
      },
    ],
  },
  {
    id: "data-structures",
    title: "Data Structures",
    color: "#c792ea",
    lessons: [
      {
        id: "py-ds-1",
        title: "Lists",
        question: "What does `fruits[-1]` return for `[\"apple\", \"banana\", \"cherry\"]`?",
        options: ["apple", "banana", "cherry", "An error"],
        correctIndex: 2,
        explanation: "Negative indices count from the end, so -1 refers to the last element.",
      },
      {
        id: "py-ds-2",
        title: "List slicing",
        question: "What does `[1, 2, 3, 4][1:3]` return?",
        options: ["[1, 2]", "[2, 3]", "[2, 3, 4]", "[1, 2, 3]"],
        correctIndex: 1,
        explanation: "Slicing [1:3] returns indices 1 up to (not including) 3: elements 2 and 3.",
      },
      {
        id: "py-ds-3",
        title: "List methods",
        question: "Which method adds an item to the end of a list?",
        options: [".add()", ".append()", ".push()", ".insert(0, x)"],
        correctIndex: 1,
        explanation: "`.append(item)` adds a single item to the end of a list.",
      },
      {
        id: "py-ds-4",
        title: "Dictionaries",
        question: "Given `person = {\"name\": \"Ada\"}`, what does `person[\"name\"]` return?",
        options: ["'name'", "\"Ada\"", "KeyError", "None"],
        correctIndex: 1,
        explanation: "Dictionary indexing with an existing key returns its value.",
      },
      {
        id: "py-ds-5",
        title: "dict.get()",
        question: "What's the advantage of `dict.get('key', default)` over `dict['key']`?",
        options: [
          "It's faster to type",
          "It returns a fallback value instead of raising an error when the key is missing",
          "It deletes the key afterwards",
          "There is no difference",
        ],
        correctIndex: 1,
        explanation: "Using .get() with a default avoids a KeyError crash when a key might not exist.",
      },
      {
        id: "py-ds-6",
        title: "Tuples vs lists",
        question: "What's the key difference between a tuple and a list?",
        options: [
          "Tuples can only hold numbers",
          "Tuples are immutable (cannot be changed) once created; lists are mutable",
          "Lists can only hold one type",
          "There is no difference",
        ],
        correctIndex: 1,
        explanation: "Tuples, written with (), are immutable — once created, their contents cannot change.",
      },
    ],
  },
  {
    id: "functions",
    title: "Functions",
    color: "#ffb454",
    lessons: [
      {
        id: "py-fn-1",
        title: "Defining functions",
        question: "Which keyword defines a function in Python?",
        options: ["function", "func", "def", "fn"],
        correctIndex: 2,
        explanation: "Python functions are defined with the `def` keyword followed by a name and parentheses.",
      },
      {
        id: "py-fn-2",
        title: "Return values",
        question: "What does a Python function return if it has no `return` statement?",
        options: ["0", "An empty string", "None", "It causes an error"],
        correctIndex: 2,
        explanation: "Without an explicit return, Python functions implicitly return None.",
      },
      {
        id: "py-fn-3",
        title: "Default parameters",
        question: "Given `def greet(name, greeting=\"Hello\"): ...`, what does `greet(\"Ada\")` use for greeting?",
        options: ["An error, since greeting is required", "\"Hello\"", "None", "An empty string"],
        correctIndex: 1,
        explanation: "Default parameter values are used automatically when the caller doesn't supply that argument.",
      },
      {
        id: "py-fn-4",
        title: "Calling functions",
        question: "What will `greet(\"Ada\", \"Hi\")` use for greeting, given the same function as above?",
        options: ["\"Hello\"", "\"Hi\"", "None", "An error"],
        correctIndex: 1,
        explanation: "Positional arguments override the default value defined in the function signature.",
      },
      {
        id: "py-fn-5",
        title: "*args and **kwargs",
        question: "What does `*args` in a function signature let you do?",
        options: [
          "Accept any number of positional arguments as a tuple",
          "Make all arguments optional strings",
          "Multiply all arguments together",
          "Accept keyword arguments only",
        ],
        correctIndex: 0,
        explanation: "`*args` collects any extra positional arguments into a tuple inside the function.",
      },
    ],
  },
  {
    id: "strings-files",
    title: "Strings & Files",
    color: "#ff8a8a",
    lessons: [
      {
        id: "py-str-1",
        title: "String methods",
        question: "What does `\"Hello World\".lower()` return?",
        options: ["HELLO WORLD", "hello world", "Hello World", "An error"],
        correctIndex: 1,
        explanation: ".lower() returns a new string with all characters lowercased.",
      },
      {
        id: "py-str-2",
        title: "Splitting strings",
        question: "What does `\"a,b,c\".split(\",\")` return?",
        options: ["\"a,b,c\"", "['a', 'b', 'c']", "('a', 'b', 'c')", "An error"],
        correctIndex: 1,
        explanation: ".split(sep) breaks a string into a list of substrings using the separator.",
      },
      {
        id: "py-str-3",
        title: "String concatenation",
        question: "What does `\"a\" + \"b\"` evaluate to?",
        options: ["\"ab\"", "2", "An error", "\"a b\""],
        correctIndex: 0,
        explanation: "The `+` operator concatenates strings.",
      },
      {
        id: "py-str-4",
        title: "Opening files",
        question: "Which is the recommended way to open and read a file safely in Python?",
        options: [
          "f = open('file.txt'); f.read()",
          "with open('file.txt') as f: data = f.read()",
          "read('file.txt')",
          "import file.txt",
        ],
        correctIndex: 1,
        explanation: "The `with` statement (a context manager) automatically closes the file even if an error occurs.",
      },
      {
        id: "py-str-5",
        title: "Why 'with'?",
        question: "Why is `with open(...) as f:` preferred over plain `open()`?",
        options: [
          "It's required by Python syntax",
          "It automatically closes the file when the block ends, even on error",
          "It reads files faster",
          "It only works with text files",
        ],
        correctIndex: 1,
        explanation: "Context managers guarantee cleanup (closing the file) regardless of how the block exits.",
      },
    ],
  },
  {
    id: "errors",
    title: "Errors & Exceptions",
    color: "#5bd1ff",
    lessons: [
      {
        id: "py-err-1",
        title: "try/except basics",
        question: "What is the purpose of a `try`/`except` block?",
        options: [
          "To speed up code execution",
          "To handle errors gracefully instead of crashing the program",
          "To define a loop",
          "To import modules",
        ],
        correctIndex: 1,
        explanation: "try/except lets your program catch and respond to errors instead of crashing.",
      },
      {
        id: "py-err-2",
        title: "Specific exceptions",
        question: "Why is catching a specific exception (like `ValueError`) better than a bare `except:`?",
        options: [
          "It runs faster",
          "It avoids accidentally hiding unrelated bugs you didn't expect to catch",
          "Bare except is invalid syntax",
          "There's no real difference",
        ],
        correctIndex: 1,
        explanation: "A bare except swallows every error, including ones you didn't anticipate, hiding real bugs.",
      },
      {
        id: "py-err-3",
        title: "raise",
        question: "What does the `raise` keyword do?",
        options: [
          "Catches an exception",
          "Manually triggers an exception",
          "Defines a new function",
          "Exits the program silently",
        ],
        correctIndex: 1,
        explanation: "`raise SomeError(...)` deliberately triggers an exception, e.g. for invalid input.",
      },
      {
        id: "py-err-4",
        title: "finally",
        question: "When does code inside a `finally` block run?",
        options: [
          "Only if no exception occurred",
          "Only if an exception occurred",
          "Always, whether or not an exception occurred",
          "Never, it's just documentation",
        ],
        correctIndex: 2,
        explanation: "finally always executes, making it ideal for cleanup like closing a connection.",
      },
      {
        id: "py-err-5",
        title: "Common exception types",
        question: "Which exception is raised when you try to convert `\"abc\"` to an int?",
        options: ["TypeError", "ValueError", "KeyError", "IndexError"],
        correctIndex: 1,
        explanation: "`int(\"abc\")` raises ValueError because the string isn't a valid number.",
      },
    ],
  },
  {
    id: "oop",
    title: "Object-Oriented Python",
    color: "#9d8cff",
    lessons: [
      {
        id: "py-oop-1",
        title: "Classes",
        question: "Which keyword defines a class in Python?",
        options: ["class", "struct", "object", "def"],
        correctIndex: 0,
        explanation: "Classes are defined with the `class` keyword.",
      },
      {
        id: "py-oop-2",
        title: "__init__",
        question: "What is the purpose of a class's `__init__` method?",
        options: [
          "To delete an instance",
          "To initialize a new instance's attributes when it's created",
          "To print the object",
          "To define a static method",
        ],
        correctIndex: 1,
        explanation: "__init__ is the constructor — it runs automatically when a new instance is created.",
      },
      {
        id: "py-oop-3",
        title: "self",
        question: "What does `self` refer to inside a class method?",
        options: [
          "The class itself",
          "The specific instance the method is called on",
          "A global variable",
          "Nothing, it's optional",
        ],
        correctIndex: 1,
        explanation: "`self` is the conventional name for the instance the method is operating on.",
      },
      {
        id: "py-oop-4",
        title: "Attributes",
        question: "Given `self.name = name` inside `__init__`, how do you access it later?",
        options: ["name", "self.name on an instance, e.g. dog.name", "Dog.name", "__name__"],
        correctIndex: 1,
        explanation: "Instance attributes are accessed via the instance: `instance.attribute`.",
      },
      {
        id: "py-oop-5",
        title: "Inheritance",
        question: "What does `class Dog(Animal):` mean?",
        options: [
          "Dog and Animal are unrelated",
          "Dog inherits attributes and methods from Animal",
          "Animal inherits from Dog",
          "This is invalid syntax",
        ],
        correctIndex: 1,
        explanation: "Putting a class in parentheses makes it the parent (base) class — Dog inherits from Animal.",
      },
      {
        id: "py-oop-6",
        title: "Methods vs functions",
        question: "What distinguishes a method from a regular function?",
        options: [
          "Methods are faster",
          "A method is a function defined inside a class, called on an instance",
          "Methods can't take arguments",
          "There's no difference",
        ],
        correctIndex: 1,
        explanation: "Methods are functions attached to a class, typically taking `self` as their first parameter.",
      },
    ],
  },
  {
    id: "advanced",
    title: "Modules & Advanced",
    color: "#5bff9d",
    lessons: [
      {
        id: "py-adv-1",
        title: "Imports",
        question: "What does `import math` allow you to do?",
        options: [
          "Use functions like math.sqrt() from the math module",
          "Install the math package",
          "Define a new module called math",
          "Nothing without pip install",
        ],
        correctIndex: 0,
        explanation: "import brings in standard library or third-party code, exposing its functions/classes.",
      },
      {
        id: "py-adv-2",
        title: "pip",
        question: "What does `pip install requests` do?",
        options: [
          "Deletes the requests package",
          "Downloads and installs the third-party 'requests' package so it can be imported",
          "Runs the requests package's test suite",
          "Updates Python itself",
        ],
        correctIndex: 1,
        explanation: "pip is Python's package manager; pip install fetches a package and makes it importable.",
      },
      {
        id: "py-adv-3",
        title: "List comprehensions",
        question: "What does `[x * 2 for x in [1, 2, 3]]` evaluate to?",
        options: ["[1, 2, 3]", "[2, 4, 6]", "6", "An error"],
        correctIndex: 1,
        explanation: "A list comprehension builds a new list by applying an expression to each item.",
      },
      {
        id: "py-adv-4",
        title: "Lambda functions",
        question: "What is a `lambda` in Python?",
        options: [
          "A loop construct",
          "A small, anonymous, single-expression function",
          "A type of exception",
          "A module for math operations",
        ],
        correctIndex: 1,
        explanation: "lambda creates a quick, unnamed function, often used inline for short operations.",
      },
      {
        id: "py-adv-5",
        title: "Virtual environments",
        question: "What problem do virtual environments solve?",
        options: [
          "They make code run faster",
          "They isolate per-project dependencies so different projects can use different package versions",
          "They automatically write your code for you",
          "They replace the need for Git",
        ],
        correctIndex: 1,
        explanation: "Without isolation, installing different versions of the same package for different projects would conflict.",
      },
      {
        id: "py-adv-6",
        title: "requirements.txt",
        question: "What is `requirements.txt` used for?",
        options: [
          "Storing the project's README",
          "Recording a project's exact dependencies so they can be reinstalled elsewhere",
          "Listing test cases",
          "Configuring the Python interpreter version only",
        ],
        correctIndex: 1,
        explanation: "requirements.txt lists package names/versions so the same environment can be recreated elsewhere.",
      },
    ],
  },
];

export const allPythonLessons = pythonUnits.flatMap((u) => u.lessons);
