import type { PathUnit } from "../lessonPathTypes";

export const vectorDbUnits: PathUnit[] = [
  {
    id: "vector-db-intro",
    title: "What Are Vector Databases?",
    color: "#5b9dff",
    lessons: [
      {
        id: "vdb-1",
        title: "Embeddings: turning meaning into numbers",
        content:
          "An embedding is a list of numbers (a vector) that represents the meaning of a piece of text, image, or other data. Similar meanings land close together in that high-dimensional space. For example, the embeddings for 'dog' and 'puppy' are much closer together than 'dog' and 'spreadsheet'. Embedding models (like OpenAI's text-embedding-ada-002 or open-source alternatives like nomic-embed) produce these vectors from raw input.",
        question: "What does it mean for two embeddings to be 'close together'?",
        options: [
          "Their text strings share many of the same characters",
          "They represent semantically similar concepts or meanings",
          "They were generated by the same API call",
          "Their vectors have the same length",
        ],
        correctIndex: 1,
        explanation: "Proximity in embedding space reflects semantic similarity — the model learns to cluster related meanings near each other during training.",
      },
      {
        id: "vdb-2",
        title: "Why regular SQL can't do semantic search",
        content:
          "A SQL WHERE clause matches exact values or patterns (LIKE '%dog%'). It can't answer 'find me sentences about animals' without you already knowing which sentences those are. Vector search computes a distance between your query embedding and every stored embedding, returning the closest matches by meaning — no keyword overlap required.",
        question: "What's the core limitation of SQL LIKE searches that vector search solves?",
        options: [
          "SQL is too slow for large datasets",
          "SQL can only match exact text or patterns, not semantic meaning",
          "SQL databases can't store text at all",
          "Vector search is always more accurate for every query type",
        ],
        correctIndex: 1,
        explanation: "LIKE '%dog%' only finds rows that literally contain the word 'dog'. Semantic search finds rows about the concept even if they use 'canine', 'puppy', or 'hound'.",
      },
      {
        id: "vdb-3",
        title: "How vector databases store and index vectors",
        content:
          "Naive vector search compares your query against every stored vector — fine for thousands of items but too slow for millions. Vector databases use approximate nearest neighbor (ANN) indexes like HNSW (Hierarchical Navigable Small World) or IVF (Inverted File Index) to prune the search space. These trade a tiny bit of recall accuracy for orders-of-magnitude speed gains.",
        question: "Why do vector databases use ANN (approximate nearest neighbor) indexes?",
        options: [
          "Exact nearest neighbor search is mathematically impossible",
          "ANN indexes are required by law for data privacy",
          "Comparing a query against every single stored vector is too slow at scale",
          "ANN always returns more accurate results than exact search",
        ],
        correctIndex: 2,
        explanation: "Exact brute-force search is O(n × d) — linear in the number of vectors times their dimension. ANN indexes dramatically reduce this by skipping large portions of the search space.",
      },
      {
        id: "vdb-4",
        title: "Popular vector databases: Pinecone, Weaviate, Chroma, pgvector",
        content:
          "Managed options like Pinecone require no infrastructure. Self-hosted options like Weaviate and Qdrant give more control. Chroma is great for local prototyping (in-memory or file-based). If you're already on PostgreSQL, pgvector adds vector columns and ANN indexes without a separate service — a smart default for apps that don't need billions of vectors.",
        question: "When would pgvector be a better choice than a dedicated vector database like Pinecone?",
        options: [
          "When you need to store more than 1 billion vectors",
          "When your app already uses PostgreSQL and your vector dataset is manageable in size",
          "When you want the fastest possible vector search at any scale",
          "When you need to search images, not text",
        ],
        correctIndex: 1,
        explanation: "pgvector is a compelling default for existing Postgres users — one less service to run, with solid ANN support up to tens of millions of vectors.",
      },
      {
        id: "vdb-5",
        title: "Metadata filtering + vector search",
        content:
          "Pure vector search returns the semantically closest items globally, but you often want 'find the most similar support ticket from Q4 2024 for the enterprise tier'. Most vector databases let you attach metadata (key-value pairs) alongside each vector and filter on that metadata before or during the nearest-neighbor search, combining precision (structured filter) with recall (semantic similarity).",
        question: "What does metadata filtering add to a vector search query?",
        options: [
          "It replaces vector similarity with keyword matching",
          "It lets you scope semantic search to a subset of records matching structured criteria",
          "It improves the quality of embeddings",
          "It eliminates the need for an ANN index",
        ],
        correctIndex: 1,
        explanation: "Metadata filters let you write queries like 'find the 5 semantically closest records where category = \"billing\" and date > 2024-01-01', combining the best of structured and semantic search.",
      },
    ],
  },
];
